-- Add migration script here
CREATE TABLE IF NOT EXISTS logs (
id SERIAL PRIMARY KEY NOT NULL,
grade VARCHAR NOT NULL,
metadata VARCHAR NULL,
created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);
