/* tslint:disable */
/* eslint-disable */
/**
 * cl-backend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const Attempt = {
    Onsight: 'Onsight',
    Flash: 'Flash',
    Redpoint: 'Redpoint',
    Fall: 'Fall'
} as const;
export type Attempt = typeof Attempt[keyof typeof Attempt];


export function instanceOfAttempt(value: any): boolean {
    for (const key in Attempt) {
        if (Object.prototype.hasOwnProperty.call(Attempt, key)) {
            if (Attempt[key as keyof typeof Attempt] === value) {
                return true;
            }
        }
    }
    return false;
}

export function AttemptFromJSON(json: any): Attempt {
    return AttemptFromJSONTyped(json, false);
}

export function AttemptFromJSONTyped(json: any, ignoreDiscriminator: boolean): Attempt {
    return json as Attempt;
}

export function AttemptToJSON(value?: Attempt | null): any {
    return value as any;
}

