/* tslint:disable */
/* eslint-disable */
/**
 * cl-backend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const ClimbType = {
    Boulder: 'Boulder',
    Sport: 'Sport'
} as const;
export type ClimbType = typeof ClimbType[keyof typeof ClimbType];


export function instanceOfClimbType(value: any): boolean {
    for (const key in ClimbType) {
        if (Object.prototype.hasOwnProperty.call(ClimbType, key)) {
            if (ClimbType[key as keyof typeof ClimbType] === value) {
                return true;
            }
        }
    }
    return false;
}

export function ClimbTypeFromJSON(json: any): ClimbType {
    return ClimbTypeFromJSONTyped(json, false);
}

export function ClimbTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): ClimbType {
    return json as ClimbType;
}

export function ClimbTypeToJSON(value?: ClimbType | null): any {
    return value as any;
}

