/* tslint:disable */
/* eslint-disable */
/**
 * cl-backend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Attempt } from './Attempt';
import {
    AttemptFromJSON,
    AttemptFromJSONTyped,
    AttemptToJSON,
} from './Attempt';
import type { Style } from './Style';
import {
    StyleFromJSON,
    StyleFromJSONTyped,
    StyleToJSON,
} from './Style';
import type { Scale } from './Scale';
import {
    ScaleFromJSON,
    ScaleFromJSONTyped,
    ScaleToJSON,
} from './Scale';
import type { ClimbType } from './ClimbType';
import {
    ClimbTypeFromJSON,
    ClimbTypeFromJSONTyped,
    ClimbTypeToJSON,
} from './ClimbType';

/**
 * 
 * @export
 * @interface Climb
 */
export interface Climb {
    /**
     * 
     * @type {Attempt}
     * @memberof Climb
     */
    attempt: Attempt;
    /**
     * 
     * @type {string}
     * @memberof Climb
     */
    climbId: string;
    /**
     * 
     * @type {ClimbType}
     * @memberof Climb
     */
    climbType: ClimbType;
    /**
     * 
     * @type {Date}
     * @memberof Climb
     */
    createdAt: Date;
    /**
     * 
     * @type {string}
     * @memberof Climb
     */
    grade: string;
    /**
     * 
     * @type {string}
     * @memberof Climb
     */
    notes?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Climb
     */
    pointer?: string | null;
    /**
     * 
     * @type {Scale}
     * @memberof Climb
     */
    scale: Scale;
    /**
     * 
     * @type {string}
     * @memberof Climb
     */
    seshId: string;
    /**
     * 
     * @type {Style}
     * @memberof Climb
     */
    style?: Style | null;
    /**
     * 
     * @type {Date}
     * @memberof Climb
     */
    updatedAt: Date;
}



/**
 * Check if a given object implements the Climb interface.
 */
export function instanceOfClimb(value: object): value is Climb {
    if (!('attempt' in value) || value['attempt'] === undefined) return false;
    if (!('climbId' in value) || value['climbId'] === undefined) return false;
    if (!('climbType' in value) || value['climbType'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('grade' in value) || value['grade'] === undefined) return false;
    if (!('scale' in value) || value['scale'] === undefined) return false;
    if (!('seshId' in value) || value['seshId'] === undefined) return false;
    if (!('updatedAt' in value) || value['updatedAt'] === undefined) return false;
    return true;
}

export function ClimbFromJSON(json: any): Climb {
    return ClimbFromJSONTyped(json, false);
}

export function ClimbFromJSONTyped(json: any, ignoreDiscriminator: boolean): Climb {
    if (json == null) {
        return json;
    }
    return {
        
        'attempt': AttemptFromJSON(json['attempt']),
        'climbId': json['climb_id'],
        'climbType': ClimbTypeFromJSON(json['climb_type']),
        'createdAt': (new Date(json['created_at'])),
        'grade': json['grade'],
        'notes': json['notes'] == null ? undefined : json['notes'],
        'pointer': json['pointer'] == null ? undefined : json['pointer'],
        'scale': ScaleFromJSON(json['scale']),
        'seshId': json['sesh_id'],
        'style': json['style'] == null ? undefined : StyleFromJSON(json['style']),
        'updatedAt': (new Date(json['updated_at'])),
    };
}

export function ClimbToJSON(value?: Climb | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'attempt': AttemptToJSON(value['attempt']),
        'climb_id': value['climbId'],
        'climb_type': ClimbTypeToJSON(value['climbType']),
        'created_at': ((value['createdAt']).toISOString()),
        'grade': value['grade'],
        'notes': value['notes'],
        'pointer': value['pointer'],
        'scale': ScaleToJSON(value['scale']),
        'sesh_id': value['seshId'],
        'style': StyleToJSON(value['style']),
        'updated_at': ((value['updatedAt']).toISOString()),
    };
}

