/* tslint:disable */
/* eslint-disable */
/**
 * cl-backend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Attempt } from './Attempt';
import {
    AttemptFromJSON,
    AttemptFromJSONTyped,
    AttemptToJSON,
} from './Attempt';
import type { Discipline } from './Discipline';
import {
    DisciplineFromJSON,
    DisciplineFromJSONTyped,
    DisciplineToJSON,
} from './Discipline';

/**
 * 
 * @export
 * @interface CreateTick
 */
export interface CreateTick {
    /**
     * 
     * @type {Attempt}
     * @memberof CreateTick
     */
    attempt: Attempt;
    /**
     * 
     * @type {Discipline}
     * @memberof CreateTick
     */
    discipline: Discipline;
    /**
     * 
     * @type {string}
     * @memberof CreateTick
     */
    lapGroup?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CreateTick
     */
    notes?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CreateTick
     */
    routeId: string;
    /**
     * 
     * @type {string}
     * @memberof CreateTick
     */
    seshId: string;
}



/**
 * Check if a given object implements the CreateTick interface.
 */
export function instanceOfCreateTick(value: object): value is CreateTick {
    if (!('attempt' in value) || value['attempt'] === undefined) return false;
    if (!('discipline' in value) || value['discipline'] === undefined) return false;
    if (!('routeId' in value) || value['routeId'] === undefined) return false;
    if (!('seshId' in value) || value['seshId'] === undefined) return false;
    return true;
}

export function CreateTickFromJSON(json: any): CreateTick {
    return CreateTickFromJSONTyped(json, false);
}

export function CreateTickFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateTick {
    if (json == null) {
        return json;
    }
    return {
        
        'attempt': AttemptFromJSON(json['attempt']),
        'discipline': DisciplineFromJSON(json['discipline']),
        'lapGroup': json['lap_group'] == null ? undefined : json['lap_group'],
        'notes': json['notes'] == null ? undefined : json['notes'],
        'routeId': json['route_id'],
        'seshId': json['sesh_id'],
    };
}

export function CreateTickToJSON(value?: CreateTick | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'attempt': AttemptToJSON(value['attempt']),
        'discipline': DisciplineToJSON(value['discipline']),
        'lap_group': value['lapGroup'],
        'notes': value['notes'],
        'route_id': value['routeId'],
        'sesh_id': value['seshId'],
    };
}

