/* tslint:disable */
/* eslint-disable */
/**
 * cl-backend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateLocation
 */
export interface CreateLocation {
    /**
     * 
     * @type {string}
     * @memberof CreateLocation
     */
    environment: string;
    /**
     * 
     * @type {string}
     * @memberof CreateLocation
     */
    name: string;
}

/**
 * Check if a given object implements the CreateLocation interface.
 */
export function instanceOfCreateLocation(value: object): value is CreateLocation {
    if (!('environment' in value) || value['environment'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function CreateLocationFromJSON(json: any): CreateLocation {
    return CreateLocationFromJSONTyped(json, false);
}

export function CreateLocationFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateLocation {
    if (json == null) {
        return json;
    }
    return {
        
        'environment': json['environment'],
        'name': json['name'],
    };
}

export function CreateLocationToJSON(value?: CreateLocation | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'environment': value['environment'],
        'name': value['name'],
    };
}

