/* tslint:disable */
/* eslint-disable */
/**
 * cl-backend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const Discipline = {
    Boulder: 'boulder',
    Sport: 'sport',
    TopRope: 'top_rope'
} as const;
export type Discipline = typeof Discipline[keyof typeof Discipline];


export function instanceOfDiscipline(value: any): boolean {
    for (const key in Discipline) {
        if (Object.prototype.hasOwnProperty.call(Discipline, key)) {
            if (Discipline[key as keyof typeof Discipline] === value) {
                return true;
            }
        }
    }
    return false;
}

export function DisciplineFromJSON(json: any): Discipline {
    return DisciplineFromJSONTyped(json, false);
}

export function DisciplineFromJSONTyped(json: any, ignoreDiscriminator: boolean): Discipline {
    return json as Discipline;
}

export function DisciplineToJSON(value?: Discipline | null): any {
    return value as any;
}

