/* tslint:disable */
/* eslint-disable */
/**
 * cl-backend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Id
 */
export interface Id {
    /**
     * 
     * @type {string}
     * @memberof Id
     */
    seshId: string;
}

/**
 * Check if a given object implements the Id interface.
 */
export function instanceOfId(value: object): value is Id {
    if (!('seshId' in value) || value['seshId'] === undefined) return false;
    return true;
}

export function IdFromJSON(json: any): Id {
    return IdFromJSONTyped(json, false);
}

export function IdFromJSONTyped(json: any, ignoreDiscriminator: boolean): Id {
    if (json == null) {
        return json;
    }
    return {
        
        'seshId': json['sesh_id'],
    };
}

export function IdToJSON(value?: Id | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'sesh_id': value['seshId'],
    };
}

