/* tslint:disable */
/* eslint-disable */
/**
 * cl-backend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Environment } from './Environment';
import {
    EnvironmentFromJSON,
    EnvironmentFromJSONTyped,
    EnvironmentToJSON,
} from './Environment';
import type { Scale } from './Scale';
import {
    ScaleFromJSON,
    ScaleFromJSONTyped,
    ScaleToJSON,
} from './Scale';
import type { Discipline } from './Discipline';
import {
    DisciplineFromJSON,
    DisciplineFromJSONTyped,
    DisciplineToJSON,
} from './Discipline';

/**
 * 
 * @export
 * @interface RouteWithLocationSqlx
 */
export interface RouteWithLocationSqlx {
    /**
     * 
     * @type {string}
     * @memberof RouteWithLocationSqlx
     */
    author: string;
    /**
     * 
     * @type {Date}
     * @memberof RouteWithLocationSqlx
     */
    createdAt: Date;
    /**
     * 
     * @type {string}
     * @memberof RouteWithLocationSqlx
     */
    description?: string | null;
    /**
     * 
     * @type {Array<Discipline>}
     * @memberof RouteWithLocationSqlx
     */
    disciplines: Array<Discipline>;
    /**
     * 
     * @type {Environment}
     * @memberof RouteWithLocationSqlx
     */
    environment: Environment;
    /**
     * 
     * @type {string}
     * @memberof RouteWithLocationSqlx
     */
    grade: string;
    /**
     * 
     * @type {string}
     * @memberof RouteWithLocationSqlx
     */
    locationAuthor: string;
    /**
     * 
     * @type {Date}
     * @memberof RouteWithLocationSqlx
     */
    locationCreatedAt: Date;
    /**
     * 
     * @type {string}
     * @memberof RouteWithLocationSqlx
     */
    locationDescription?: string | null;
    /**
     * 
     * @type {string}
     * @memberof RouteWithLocationSqlx
     */
    locationId: string;
    /**
     * 
     * @type {Date}
     * @memberof RouteWithLocationSqlx
     */
    locationUpdatedAt: Date;
    /**
     * 
     * @type {string}
     * @memberof RouteWithLocationSqlx
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof RouteWithLocationSqlx
     */
    routeId: string;
    /**
     * 
     * @type {Scale}
     * @memberof RouteWithLocationSqlx
     */
    scale: Scale;
    /**
     * 
     * @type {Date}
     * @memberof RouteWithLocationSqlx
     */
    updatedAt: Date;
}



/**
 * Check if a given object implements the RouteWithLocationSqlx interface.
 */
export function instanceOfRouteWithLocationSqlx(value: object): value is RouteWithLocationSqlx {
    if (!('author' in value) || value['author'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('disciplines' in value) || value['disciplines'] === undefined) return false;
    if (!('environment' in value) || value['environment'] === undefined) return false;
    if (!('grade' in value) || value['grade'] === undefined) return false;
    if (!('locationAuthor' in value) || value['locationAuthor'] === undefined) return false;
    if (!('locationCreatedAt' in value) || value['locationCreatedAt'] === undefined) return false;
    if (!('locationId' in value) || value['locationId'] === undefined) return false;
    if (!('locationUpdatedAt' in value) || value['locationUpdatedAt'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('routeId' in value) || value['routeId'] === undefined) return false;
    if (!('scale' in value) || value['scale'] === undefined) return false;
    if (!('updatedAt' in value) || value['updatedAt'] === undefined) return false;
    return true;
}

export function RouteWithLocationSqlxFromJSON(json: any): RouteWithLocationSqlx {
    return RouteWithLocationSqlxFromJSONTyped(json, false);
}

export function RouteWithLocationSqlxFromJSONTyped(json: any, ignoreDiscriminator: boolean): RouteWithLocationSqlx {
    if (json == null) {
        return json;
    }
    return {
        
        'author': json['author'],
        'createdAt': (new Date(json['created_at'])),
        'description': json['description'] == null ? undefined : json['description'],
        'disciplines': ((json['disciplines'] as Array<any>).map(DisciplineFromJSON)),
        'environment': EnvironmentFromJSON(json['environment']),
        'grade': json['grade'],
        'locationAuthor': json['location_author'],
        'locationCreatedAt': (new Date(json['location_created_at'])),
        'locationDescription': json['location_description'] == null ? undefined : json['location_description'],
        'locationId': json['location_id'],
        'locationUpdatedAt': (new Date(json['location_updated_at'])),
        'name': json['name'],
        'routeId': json['route_id'],
        'scale': ScaleFromJSON(json['scale']),
        'updatedAt': (new Date(json['updated_at'])),
    };
}

export function RouteWithLocationSqlxToJSON(value?: RouteWithLocationSqlx | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'author': value['author'],
        'created_at': ((value['createdAt']).toISOString()),
        'description': value['description'],
        'disciplines': ((value['disciplines'] as Array<any>).map(DisciplineToJSON)),
        'environment': EnvironmentToJSON(value['environment']),
        'grade': value['grade'],
        'location_author': value['locationAuthor'],
        'location_created_at': ((value['locationCreatedAt']).toISOString()),
        'location_description': value['locationDescription'],
        'location_id': value['locationId'],
        'location_updated_at': ((value['locationUpdatedAt']).toISOString()),
        'name': value['name'],
        'route_id': value['routeId'],
        'scale': ScaleToJSON(value['scale']),
        'updated_at': ((value['updatedAt']).toISOString()),
    };
}

