/* tslint:disable */
/* eslint-disable */
/**
 * cl-backend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const Scale = {
    Verm: 'verm',
    Font: 'font',
    Yosemite: 'yosemite',
    French: 'french'
} as const;
export type Scale = typeof Scale[keyof typeof Scale];


export function instanceOfScale(value: any): boolean {
    for (const key in Scale) {
        if (Object.prototype.hasOwnProperty.call(Scale, key)) {
            if (Scale[key as keyof typeof Scale] === value) {
                return true;
            }
        }
    }
    return false;
}

export function ScaleFromJSON(json: any): Scale {
    return ScaleFromJSONTyped(json, false);
}

export function ScaleFromJSONTyped(json: any, ignoreDiscriminator: boolean): Scale {
    return json as Scale;
}

export function ScaleToJSON(value?: Scale | null): any {
    return value as any;
}

