/* tslint:disable */
/* eslint-disable */
/**
 * cl-backend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Sesh
 */
export interface Sesh {
    /**
     * 
     * @type {Date}
     * @memberof Sesh
     */
    createdAt: Date;
    /**
     * 
     * @type {Date}
     * @memberof Sesh
     */
    end?: Date | null;
    /**
     * 
     * @type {string}
     * @memberof Sesh
     */
    locationId: string;
    /**
     * 
     * @type {string}
     * @memberof Sesh
     */
    notes?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Sesh
     */
    seshId: string;
    /**
     * 
     * @type {Date}
     * @memberof Sesh
     */
    start: Date;
    /**
     * 
     * @type {Date}
     * @memberof Sesh
     */
    updatedAt: Date;
    /**
     * 
     * @type {string}
     * @memberof Sesh
     */
    userId: string;
}

/**
 * Check if a given object implements the Sesh interface.
 */
export function instanceOfSesh(value: object): value is Sesh {
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('locationId' in value) || value['locationId'] === undefined) return false;
    if (!('seshId' in value) || value['seshId'] === undefined) return false;
    if (!('start' in value) || value['start'] === undefined) return false;
    if (!('updatedAt' in value) || value['updatedAt'] === undefined) return false;
    if (!('userId' in value) || value['userId'] === undefined) return false;
    return true;
}

export function SeshFromJSON(json: any): Sesh {
    return SeshFromJSONTyped(json, false);
}

export function SeshFromJSONTyped(json: any, ignoreDiscriminator: boolean): Sesh {
    if (json == null) {
        return json;
    }
    return {
        
        'createdAt': (new Date(json['created_at'])),
        'end': json['end'] == null ? undefined : (new Date(json['end'])),
        'locationId': json['location_id'],
        'notes': json['notes'] == null ? undefined : json['notes'],
        'seshId': json['sesh_id'],
        'start': (new Date(json['start'])),
        'updatedAt': (new Date(json['updated_at'])),
        'userId': json['user_id'],
    };
}

export function SeshToJSON(value?: Sesh | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'created_at': ((value['createdAt']).toISOString()),
        'end': value['end'] == null ? undefined : ((value['end'] as any).toISOString()),
        'location_id': value['locationId'],
        'notes': value['notes'],
        'sesh_id': value['seshId'],
        'start': ((value['start']).toISOString()),
        'updated_at': ((value['updatedAt']).toISOString()),
        'user_id': value['userId'],
    };
}

