/* tslint:disable */
/* eslint-disable */
/**
 * cl-backend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const Style = {
    TopRope: 'top_rope',
    Lead: 'lead'
} as const;
export type Style = typeof Style[keyof typeof Style];


export function instanceOfStyle(value: any): boolean {
    for (const key in Style) {
        if (Object.prototype.hasOwnProperty.call(Style, key)) {
            if (Style[key as keyof typeof Style] === value) {
                return true;
            }
        }
    }
    return false;
}

export function StyleFromJSON(json: any): Style {
    return StyleFromJSONTyped(json, false);
}

export function StyleFromJSONTyped(json: any, ignoreDiscriminator: boolean): Style {
    return json as Style;
}

export function StyleToJSON(value?: Style | null): any {
    return value as any;
}

