/* tslint:disable */
/* eslint-disable */
/**
 * cl-backend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TickSearchParams
 */
export interface TickSearchParams {
    /**
     * 
     * @type {string}
     * @memberof TickSearchParams
     */
    seshId: string;
}

/**
 * Check if a given object implements the TickSearchParams interface.
 */
export function instanceOfTickSearchParams(value: object): value is TickSearchParams {
    if (!('seshId' in value) || value['seshId'] === undefined) return false;
    return true;
}

export function TickSearchParamsFromJSON(json: any): TickSearchParams {
    return TickSearchParamsFromJSONTyped(json, false);
}

export function TickSearchParamsFromJSONTyped(json: any, ignoreDiscriminator: boolean): TickSearchParams {
    if (json == null) {
        return json;
    }
    return {
        
        'seshId': json['sesh_id'],
    };
}

export function TickSearchParamsToJSON(value?: TickSearchParams | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'sesh_id': value['seshId'],
    };
}

