/* tslint:disable */
/* eslint-disable */
/**
 * cl-backend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Attempt } from './Attempt';
import {
    AttemptFromJSON,
    AttemptFromJSONTyped,
    AttemptToJSON,
} from './Attempt';
import type { Discipline } from './Discipline';
import {
    DisciplineFromJSON,
    DisciplineFromJSONTyped,
    DisciplineToJSON,
} from './Discipline';

/**
 * 
 * @export
 * @interface TickRow
 */
export interface TickRow {
    /**
     * 
     * @type {Attempt}
     * @memberof TickRow
     */
    attempt: Attempt;
    /**
     * 
     * @type {Date}
     * @memberof TickRow
     */
    createdAt: Date;
    /**
     * 
     * @type {Discipline}
     * @memberof TickRow
     */
    discipline: Discipline;
    /**
     * 
     * @type {string}
     * @memberof TickRow
     */
    lapGroup?: string | null;
    /**
     * 
     * @type {string}
     * @memberof TickRow
     */
    notes?: string | null;
    /**
     * 
     * @type {string}
     * @memberof TickRow
     */
    routeId: string;
    /**
     * 
     * @type {string}
     * @memberof TickRow
     */
    seshId: string;
    /**
     * 
     * @type {string}
     * @memberof TickRow
     */
    tickId: string;
    /**
     * 
     * @type {Date}
     * @memberof TickRow
     */
    updatedAt: Date;
}



/**
 * Check if a given object implements the TickRow interface.
 */
export function instanceOfTickRow(value: object): value is TickRow {
    if (!('attempt' in value) || value['attempt'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('discipline' in value) || value['discipline'] === undefined) return false;
    if (!('routeId' in value) || value['routeId'] === undefined) return false;
    if (!('seshId' in value) || value['seshId'] === undefined) return false;
    if (!('tickId' in value) || value['tickId'] === undefined) return false;
    if (!('updatedAt' in value) || value['updatedAt'] === undefined) return false;
    return true;
}

export function TickRowFromJSON(json: any): TickRow {
    return TickRowFromJSONTyped(json, false);
}

export function TickRowFromJSONTyped(json: any, ignoreDiscriminator: boolean): TickRow {
    if (json == null) {
        return json;
    }
    return {
        
        'attempt': AttemptFromJSON(json['attempt']),
        'createdAt': (new Date(json['created_at'])),
        'discipline': DisciplineFromJSON(json['discipline']),
        'lapGroup': json['lap_group'] == null ? undefined : json['lap_group'],
        'notes': json['notes'] == null ? undefined : json['notes'],
        'routeId': json['route_id'],
        'seshId': json['sesh_id'],
        'tickId': json['tick_id'],
        'updatedAt': (new Date(json['updated_at'])),
    };
}

export function TickRowToJSON(value?: TickRow | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'attempt': AttemptToJSON(value['attempt']),
        'created_at': ((value['createdAt']).toISOString()),
        'discipline': DisciplineToJSON(value['discipline']),
        'lap_group': value['lapGroup'],
        'notes': value['notes'],
        'route_id': value['routeId'],
        'sesh_id': value['seshId'],
        'tick_id': value['tickId'],
        'updated_at': ((value['updatedAt']).toISOString()),
    };
}

