/* tslint:disable */
/* eslint-disable */
/**
 * cl-backend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Scale } from './Scale';
import {
    ScaleFromJSON,
    ScaleFromJSONTyped,
    ScaleToJSON,
} from './Scale';
import type { Discipline } from './Discipline';
import {
    DisciplineFromJSON,
    DisciplineFromJSONTyped,
    DisciplineToJSON,
} from './Discipline';

/**
 * 
 * @export
 * @interface UpdateRoute
 */
export interface UpdateRoute {
    /**
     * 
     * @type {string}
     * @memberof UpdateRoute
     */
    description?: string | null;
    /**
     * 
     * @type {Array<Discipline>}
     * @memberof UpdateRoute
     */
    disciplines?: Array<Discipline> | null;
    /**
     * 
     * @type {string}
     * @memberof UpdateRoute
     */
    grade?: string | null;
    /**
     * 
     * @type {Scale}
     * @memberof UpdateRoute
     */
    scale?: Scale | null;
}



/**
 * Check if a given object implements the UpdateRoute interface.
 */
export function instanceOfUpdateRoute(value: object): value is UpdateRoute {
    return true;
}

export function UpdateRouteFromJSON(json: any): UpdateRoute {
    return UpdateRouteFromJSONTyped(json, false);
}

export function UpdateRouteFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateRoute {
    if (json == null) {
        return json;
    }
    return {
        
        'description': json['description'] == null ? undefined : json['description'],
        'disciplines': json['disciplines'] == null ? undefined : ((json['disciplines'] as Array<any>).map(DisciplineFromJSON)),
        'grade': json['grade'] == null ? undefined : json['grade'],
        'scale': json['scale'] == null ? undefined : ScaleFromJSON(json['scale']),
    };
}

export function UpdateRouteToJSON(value?: UpdateRoute | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'description': value['description'],
        'disciplines': value['disciplines'] == null ? undefined : ((value['disciplines'] as Array<any>).map(DisciplineToJSON)),
        'grade': value['grade'],
        'scale': ScaleToJSON(value['scale']),
    };
}

