/* tslint:disable */
/* eslint-disable */
/**
 * cl-backend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Environment } from './Environment';
import {
    EnvironmentFromJSON,
    EnvironmentFromJSONTyped,
    EnvironmentToJSON,
} from './Environment';

/**
 * 
 * @export
 * @interface UpdateLocation
 */
export interface UpdateLocation {
    /**
     * 
     * @type {string}
     * @memberof UpdateLocation
     */
    description?: string | null;
    /**
     * 
     * @type {Environment}
     * @memberof UpdateLocation
     */
    environment?: Environment | null;
    /**
     * 
     * @type {string}
     * @memberof UpdateLocation
     */
    name?: string | null;
}



/**
 * Check if a given object implements the UpdateLocation interface.
 */
export function instanceOfUpdateLocation(value: object): value is UpdateLocation {
    return true;
}

export function UpdateLocationFromJSON(json: any): UpdateLocation {
    return UpdateLocationFromJSONTyped(json, false);
}

export function UpdateLocationFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateLocation {
    if (json == null) {
        return json;
    }
    return {
        
        'description': json['description'] == null ? undefined : json['description'],
        'environment': json['environment'] == null ? undefined : EnvironmentFromJSON(json['environment']),
        'name': json['name'] == null ? undefined : json['name'],
    };
}

export function UpdateLocationToJSON(value?: UpdateLocation | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'description': value['description'],
        'environment': EnvironmentToJSON(value['environment']),
        'name': value['name'],
    };
}

