/* tslint:disable */
/* eslint-disable */
/**
 * cl-backend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  CreateSesh,
  SeshRow,
  SeshWithLocation,
  SeshWithLocationAndTicks,
  UpdateLocation,
} from '../models/index';
import {
    CreateSeshFromJSON,
    CreateSeshToJSON,
    SeshRowFromJSON,
    SeshRowToJSON,
    SeshWithLocationFromJSON,
    SeshWithLocationToJSON,
    SeshWithLocationAndTicksFromJSON,
    SeshWithLocationAndTicksToJSON,
    UpdateLocationFromJSON,
    UpdateLocationToJSON,
} from '../models/index';

export interface CreateSeshRequest {
    createSesh: CreateSesh;
}

export interface DeleteSeshRequest {
    seshId: string;
}

export interface GetSeshBySeshIdRequest {
    seshId: string;
}

export interface UpdateSeshBySeshIdRequest {
    seshId: string;
    updateLocation: UpdateLocation;
}

/**
 * ClBackendapiseshesseshesControllerApi - interface
 * 
 * @export
 * @interface ClBackendapiseshesseshesControllerApiInterface
 */
export interface ClBackendapiseshesseshesControllerApiInterface {
    /**
     * 
     * @param {CreateSesh} createSesh 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ClBackendapiseshesseshesControllerApiInterface
     */
    createSeshRaw(requestParameters: CreateSeshRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SeshWithLocation>>;

    /**
     */
    createSesh(requestParameters: CreateSeshRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SeshWithLocation>;

    /**
     * 
     * @param {string} seshId sesh id
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ClBackendapiseshesseshesControllerApiInterface
     */
    deleteSeshRaw(requestParameters: DeleteSeshRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>>;

    /**
     */
    deleteSesh(requestParameters: DeleteSeshRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void>;

    /**
     * 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ClBackendapiseshesseshesControllerApiInterface
     */
    getActiveSeshRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SeshWithLocation>>;

    /**
     */
    getActiveSesh(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SeshWithLocation>;

    /**
     * 
     * @param {string} seshId sesh id
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ClBackendapiseshesseshesControllerApiInterface
     */
    getSeshBySeshIdRaw(requestParameters: GetSeshBySeshIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SeshWithLocationAndTicks>>;

    /**
     */
    getSeshBySeshId(requestParameters: GetSeshBySeshIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SeshWithLocationAndTicks>;

    /**
     * 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ClBackendapiseshesseshesControllerApiInterface
     */
    searchSeshesRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<SeshWithLocation>>>;

    /**
     */
    searchSeshes(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<SeshWithLocation>>;

    /**
     * 
     * @param {string} seshId sesh id
     * @param {UpdateLocation} updateLocation 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ClBackendapiseshesseshesControllerApiInterface
     */
    updateSeshBySeshIdRaw(requestParameters: UpdateSeshBySeshIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SeshRow>>;

    /**
     */
    updateSeshBySeshId(requestParameters: UpdateSeshBySeshIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SeshRow>;

}

/**
 * 
 */
export class ClBackendapiseshesseshesControllerApi extends runtime.BaseAPI implements ClBackendapiseshesseshesControllerApiInterface {

    /**
     */
    async createSeshRaw(requestParameters: CreateSeshRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SeshWithLocation>> {
        if (requestParameters['createSesh'] == null) {
            throw new runtime.RequiredError(
                'createSesh',
                'Required parameter "createSesh" was null or undefined when calling createSesh().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("token_jwt", ["general"]);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/seshes`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateSeshToJSON(requestParameters['createSesh']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SeshWithLocationFromJSON(jsonValue));
    }

    /**
     */
    async createSesh(requestParameters: CreateSeshRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SeshWithLocation> {
        const response = await this.createSeshRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async deleteSeshRaw(requestParameters: DeleteSeshRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['seshId'] == null) {
            throw new runtime.RequiredError(
                'seshId',
                'Required parameter "seshId" was null or undefined when calling deleteSesh().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("token_jwt", ["general"]);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/seshes/{sesh_id}`.replace(`{${"sesh_id"}}`, encodeURIComponent(String(requestParameters['seshId']))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async deleteSesh(requestParameters: DeleteSeshRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.deleteSeshRaw(requestParameters, initOverrides);
    }

    /**
     */
    async getActiveSeshRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SeshWithLocation>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("token_jwt", ["general"]);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/seshes/active`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SeshWithLocationFromJSON(jsonValue));
    }

    /**
     */
    async getActiveSesh(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SeshWithLocation> {
        const response = await this.getActiveSeshRaw(initOverrides);
        return await response.value();
    }

    /**
     */
    async getSeshBySeshIdRaw(requestParameters: GetSeshBySeshIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SeshWithLocationAndTicks>> {
        if (requestParameters['seshId'] == null) {
            throw new runtime.RequiredError(
                'seshId',
                'Required parameter "seshId" was null or undefined when calling getSeshBySeshId().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("token_jwt", ["general"]);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/seshes/{sesh_id}`.replace(`{${"sesh_id"}}`, encodeURIComponent(String(requestParameters['seshId']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SeshWithLocationAndTicksFromJSON(jsonValue));
    }

    /**
     */
    async getSeshBySeshId(requestParameters: GetSeshBySeshIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SeshWithLocationAndTicks> {
        const response = await this.getSeshBySeshIdRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async searchSeshesRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<SeshWithLocation>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("token_jwt", ["general"]);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/seshes`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(SeshWithLocationFromJSON));
    }

    /**
     */
    async searchSeshes(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<SeshWithLocation>> {
        const response = await this.searchSeshesRaw(initOverrides);
        return await response.value();
    }

    /**
     */
    async updateSeshBySeshIdRaw(requestParameters: UpdateSeshBySeshIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SeshRow>> {
        if (requestParameters['seshId'] == null) {
            throw new runtime.RequiredError(
                'seshId',
                'Required parameter "seshId" was null or undefined when calling updateSeshBySeshId().'
            );
        }

        if (requestParameters['updateLocation'] == null) {
            throw new runtime.RequiredError(
                'updateLocation',
                'Required parameter "updateLocation" was null or undefined when calling updateSeshBySeshId().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("token_jwt", ["general"]);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/seshes/{sesh_id}`.replace(`{${"sesh_id"}}`, encodeURIComponent(String(requestParameters['seshId']))),
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: UpdateLocationToJSON(requestParameters['updateLocation']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SeshRowFromJSON(jsonValue));
    }

    /**
     */
    async updateSeshBySeshId(requestParameters: UpdateSeshBySeshIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SeshRow> {
        const response = await this.updateSeshBySeshIdRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
